<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<?php if ($block->getCollection()->getSize()): ?>
    <div class="toolbar toolbar-products" data-mage-init='<?php /* @escapeNotVerified */ echo $block->getWidgetOptionsJson(); ?>'>
        <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
        <?php endif; ?>

        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>

        <?php echo $block->getPagerHtml() ?>

        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>

        <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
        <?php endif; ?>
    </div>
    <script>
        require([
            'jquery',
            'matchMedia'
        ], function ($, mediaCheck) {
            $( document ).ready(function() {

            });

            mediaCheck({
                media: '(min-width: 1024px)',
                // Switch to Desktop Version
                entry: function () {
                    $('.catalog-nav-mobile + .toolbar-products').append(
                        $('.catalog-nav-mobile > .field.limiter'),
                        $('.catalog-nav-mobile > .toolbar-sorter.sorter')
                    );
                },
                // Switch to Mobile Version
                exit: function () {
                    $('.catalog-nav-mobile').prepend(
                        $('.catalog-nav-mobile + .toolbar-products > .field.limiter'),
                        $('.catalog-nav-mobile + .toolbar-products > .toolbar-sorter.sorter')
                    );
                }
            });
        });

    </script>

<?php endif ?>
