<?php

// autoload_52.php generated by xrstf/composer-php52

require_once dirname(__FILE__) . '/composer'.'/autoload_real_52.php';

return ComposerAutoloaderInit2414b89647bf339bd0901d6f243a5e72::getLoader();
