<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
use \Magento\CatalogSearch\Model\Layer\Filter\Category;
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */ echo $filtered; ?>">
            <strong data-role="title"><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
        </div>
        <div class="block-content filter-content">
            <?php echo $block->getChildHtml('state') ?>

            <?php $wrapOptions = false; $filterHeader = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <?php if (!$wrapOptions): ?>
                        <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
                    <?php  $wrapOptions = true; endif; ?>
                    <?php if ($filter instanceof Category): ?>
                        <?php

                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $cat_helper= $objectManager->create('\Magento\Catalog\Helper\Category');
                        $categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository');


                        $currentCat = $objectManager->get('Magento\Framework\Registry')->registry('current_category');


                        if (!$currentCat){
                        continue;
                        }

                        ?>

                        <div class="filter-options-item categories">
                            <div class="filter-options-title"><?php /* @escapeNotVerified */ echo __($filter->getName()) ?></div>
                            <div class="filter-options-content" id="categories-list-filter-desktop">
                                <?php


                                $categoryObj = $categoryRepository->get($currentCat->getId());
                                $subcategories = $categoryObj->getChildrenCategories();

                                $subCatReorder = [];
                                foreach($subcategories as $cat){
                                    if (!isset($subCatReorder[$cat->getPosition()]))
                                    {
                                        $subCatReorder[$cat->getPosition()] = [];
                                    }
                                    $subCatReorder[$cat->getPosition()][$cat->getName()] = $cat;
                                }
                                $subcategories = [];
                                foreach($subCatReorder as $catPositions){
                                    sort($catPositions);
                                    foreach($catPositions as $cat){
                                        $subcategories[] = $cat;
                                    }
                                }

                                ?>
                                <ol class="items sidebar-magemenu">
                                   <?php foreach($subcategories as $cat): ?>
                                       <?php
                                       $cateinstance = $objectManager->create('Magento\Catalog\Model\CategoryFactory');
                                       $allcategoryproduct = $cateinstance->create()
                                           ->load($cat->getId())
                                           ->getProductCollection()
                                           ->addAttributeToSelect('*');
                                       if ($allcategoryproduct->count()<1){
                                           //skpiing category if prods 0
                                           continue;
                                       }
                                       ?>
                                       <li class="item">
                                           <?php $c = $categoryRepository->get($cat->getId()); ?>
                                           <a class="attribute-name" href="<?= $cat_helper->getCategoryUrl($c); ?>">
                                            <?= $cat->getName() ?>
                                               <span class="count">

                                                   <?= $allcategoryproduct->count(); ?>
                                               </span>
                                           </a>
                                           <?php $subcats = $cat->getChildrenCategories() ?>
                                           <?php if ($subcats->count()>0): ?>

                                               <?php

                                               $subCatReorder = [];
                                               foreach($subcats as $scat){
                                                   if (!isset($subCatReorder[$scat->getPosition()]))
                                                   {
                                                       $subCatReorder[$scat->getPosition()] = [];
                                                   }
                                                   $subCatReorder[$scat->getPosition()][$scat->getName()] = $scat;
                                               }
                                               $subcats = [];
                                               foreach($subCatReorder as $catPositions){
                                                   sort($catPositions);
                                                   foreach($catPositions as $scat){
                                                       $subcats[] = $scat;
                                                   }
                                               }
                                               ?>
                                           <ul class="sidebar-magemenu-submenu">
                                               <li class="item search-item">
                                                   <?php
                                                   /**
                                                    * Copyright © Magento, Inc. All rights reserved.
                                                    * See COPYING.txt for license details.
                                                    */

                                                   // @codingStandardsIgnoreFile
                                                   ?>
                                                   <?php
                                                   /** @var $block \Magento\Framework\View\Element\Template */
                                                   /** @var $helper \Magento\Search\Helper\Data */
                                                   $helper = $this->helper('Magento\Search\Helper\Data');
                                                   ?>

                                                           <form class="form minisearch" id="search_mini_form" action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>" method="get">
                                                               <div class="field search">
                                                                   <div class="control">
                                                                       <input id="search"
                                                                              data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?= /* @escapeNotVerified */ $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]) ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                                                                              type="text"
                                                                              name="<?= /* @escapeNotVerified */ $helper->getQueryParamName() ?>"
                                                                              value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText() ?>"
                                                                              placeholder="<?= /* @escapeNotVerified */ __('Search entire store here...') ?>"
                                                                              class="input-text"
                                                                              maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength() ?>"
                                                                              role="combobox"
                                                                              aria-haspopup="false"
                                                                              aria-autocomplete="both"
                                                                              autocomplete="off"/>
                                                                       <div id="search_autocomplete" class="search-autocomplete"></div>
                                                                       <?= $block->getChildHtml() ?>
                                                                   </div>
                                                               </div>
                                                           </form>

                                               </li>
                                                <?php foreach($subcats as $scat): ?>
                                                    <?php $c = $categoryRepository->get($scat->getId()); ?>
                                                   <li class="item">
                                                       <a class="attribute-name" href="<?= $cat_helper->getCategoryUrl($c); ?>">
                                                           <?= $scat->getName(); ?>&nbsp;
                                                           <i class="long arrow right icon"></i>
                                                       </a>
                                                   </li>
                                                <?php endforeach; ?>
                                           </ul>
                                           <?php endif; ?>
                                       </li>
                                    <?php endforeach; ?>
                                </ol>
                            </div>
                        </div>

                    <?php else: ?>
                        <?php if (!$filterHeader): ?>
                            <div class="filter-options-title attributes-title"><span><?php echo __('Filter') ?></span>
                                <?php if ($block->getLayer()->getState()->getFilters()): ?>
                                    <div class="block-actions filter-actions">
                                        <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span>- <?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php $filterHeader = true; endif; ?>
                        <div data-role="collapsible" class="filter-options-item" >
                            <div data-role="title" class="filter-options-title"><?php /* @escapeNotVerified */ echo __($filter->getName()) ?></div>
                            <div data-role="content" class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
                        </div>
                    <?php endif;?>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
            <?php else: ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
