<div class="footer-contacts">
    <div class="title"><span><?php echo __('Contacts') ?></span></div>
    <div class="item icon-place">Address: Varkalu 13A, Riga, Latvia, LV-1067</div>
    <div class="item icon-phone">Phone: <a href="tel:+371 66103003">+371 66103003</a>,<a href="tel:+371 20277153"> +371 20277153</a></div>
    <div class="item icon-envelope">Email: <a href="mailto:info@amedical.eu">info@amedical.eu</a></div>
</div>