<?php
$contacts = $block->getProductCategoryContacts();
?>
<?php if (is_array($contacts)): ?>
    <div class="flex-container">
        <div class="row">
            <div class="info-block category-contacts bordered col-m-12">
                <img src="<?php echo $block->getViewFileUrl('images/phone-icon.png') ?>" />
                <div class="content">
                    <span><?php echo __('Contact Person') ?>: <br /><?php echo $contacts['name'] ?>
                        <a href="tel:<?php echo $contacts['phone'] ?>"><?php echo $contacts['phone'] ?></a>
                    </span>
                </div>
            </div>
            <div class="info-block bordered col-m-12">
                <span><img src="<?php echo $block->getViewFileUrl('images/delivery.jpg') ?>"/></span>
                <div class="content"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('free_delivery_block')->toHtml();?></div>
            </div>
        </div>
    </div>
<?php endif; ?>
